services:
  postgres:
    hostname: blueprints
    container_name: blueprintsdatabase
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "development", "-U", "developer"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/.volumes/blueprintsdatabase/data:/var/lib/postgresql/data

  fastapi:
    build: ./backend/
    hostname: blueprints
    container_name: blueprintsbackend
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/app:/app/app

networks:
  default:
    name: blueprints-network
