services:
  fastapi:
    build: .
    env_file: ".env"
    hostname: blueprints
    container_name: blueprintsbackend
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app/app

networks:
  default:
    name: blueprints-network
