services:
  postgres:
    hostname: blueprints
    container_name: blueprintsdatabase
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${BP_POSTGRES__USER}
      POSTGRES_PASSWORD: ${BP_POSTGRES__PASSWORD}
      POSTGRES_DB: ${BP_POSTGRES__DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "$BP_POSTGRES__DB", "-U", "$BP_POSTGRES__USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .volumes/blueprintsdatabase/data:/var/lib/postgresql/data

  fastapi:
    build: .
    env_file: ".env"
    hostname: blueprints
    container_name: blueprintsbackend
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app

networks:
  default:
    name: blueprints-network
