@startuml
User "1" -- "*" ListTemplate : creates >
User "1" -- "*" Reminder : creates >
User *-- UserAccount : contains >
ListTemplate "*" -- "1" Model : generates <

class User {
 id: UUID
 nickname: String
 avatar: String
}

class UserAccount <<subresource>> {
 id: String
 subscription: Subscription
 subscriptionChangeDate: String
 email: String
}

class ListTemplate {
 id: UUID
 userId: String
 modelId: String
 title: String
 task: String
 checkList: CheckListItem[]
 created: String
 deleted: String
}

class Model {
 id: UUID
 name: String
 model: String
 type: ModelType
 instruction: String
 top_p: Float
 seed: Integer
 temperature: Float
 response_format: String
}


class Reminder {
 id: UUID
 task: TaskT
 interval: ReminderInterval
}

class Operation {
 id: UUID
 done: Boolean
 result: ResultT
 metadata: MetadataT
}

interface CheckListItem <<interface>> {
 checked: Boolean
 text: String
 note: String
}

enum ReminderInterval <<enumeration>> {
 DAY
 WEEK
 BIWEEK
 MONTH
 YEAR
}

enum Subscription <<enumeration>> {
 FREE
 PRO
}

enum ModelType <<enumeration>> {
  INSTRUCTIONS
  QUESTIONS
}

@enduml